In [39]:
%load_ext autoreload
%autoreload 2

from eeg_eye.dataset import EEGEyeDataset
from eeg_eye.data import load
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
data_set = EEGEyeDataset(window_size=10, stride=5)

2026-03-22 10:29:14.519 | INFO     | eeg_eye.data:download:29 - File exists


In [4]:
window = 50
stride = 50

In [5]:
cumcount = np.concatenate([[0], data_set.cumulative_count])
cumcount

array([  0,   0,   2,  14,  22,  27,  36,  44,  48,  48,  55,  74,  90,
       102, 115, 162, 202, 220, 232, 232, 235, 235, 257, 257, 269, 269])

In [6]:
idx = 0

search = np.searchsorted(cumcount, idx, side='right')
previous_len = cumcount[search - 1]
window = data_set[idx - previous_len]

In [7]:
window

(tensor([[4329.2300, 4009.2300, 4289.2300, 4148.2100, 4350.2598, 4586.1499,
          4096.9199, 4641.0298, 4222.0498, 4238.4600, 4211.2798, 4280.5098,
          4635.8999, 4393.8501],
         [4324.6201, 4004.6201, 4293.8501, 4148.7202, 4342.0498, 4586.6699,
          4097.4399, 4638.9702, 4210.7700, 4226.6699, 4207.6899, 4279.4902,
          4632.8198, 4384.1001],
         [4327.6899, 4006.6699, 4295.3799, 4156.4102, 4336.9199, 4583.5898,
          4096.9199, 4630.2598, 4207.6899, 4222.0498, 4206.6699, 4282.0498,
          4628.7202, 4389.2300],
         [4328.7202, 4011.7900, 4296.4102, 4155.8999, 4343.5898, 4582.5601,
          4097.4399, 4630.7700, 4217.4399, 4235.3799, 4210.7700, 4287.6899,
          4632.3101, 4396.4102],
         [4326.1499, 4011.7900, 4292.3101, 4151.2798, 4347.6899, 4586.6699,
          4095.8999, 4627.6899, 4210.7700, 4244.1001, 4212.8198, 4288.2100,
          4632.8198, 4398.4600],
         [4321.0298, 4004.6201, 4284.1001, 4153.3301, 4345.6401, 4587.1802,

In [19]:
x, y =data_set[0]

In [20]:
x.shape

torch.Size([10, 14])

In [23]:
len(data_set)

2940

In [30]:
from eeg_eye.loader import get_dataloader
loader = get_dataloader()
x, y = next(iter(loader))
print(x.shape, y.shape)

2026-03-22 10:41:08.435 | INFO     | eeg_eye.data:download:29 - File exists


torch.Size([4, 50, 14]) torch.Size([4])


In [31]:
from eeg_eye.model import GRUmodel
from eeg_eye.config import ModelConfig

model = GRUmodel(ModelConfig())
x, y = next(iter(loader))
output = model(x)
print(output.shape)

torch.Size([4, 1])


In [32]:
output[1]

tensor([0.5469], grad_fn=<SelectBackward0>)

In [1]:
from eeg_eye.loader import get_dataloader
from eeg_eye.data import DEFAULT_DATA_DIR

train_loader = get_dataloader(
    data_dir=DEFAULT_DATA_DIR,
    batch_size=16,
    window_size=50,
    stride=50,
    split_ratio=0.8,
    split="train"
)

val_loader = get_dataloader(
    data_dir=DEFAULT_DATA_DIR,
    batch_size=16,
    window_size=50,
    stride=50,
    split_ratio=0.8,
    split="val"
)

print(len(train_loader.dataset), len(val_loader.dataset))

2026-03-22 16:19:15.276 | INFO     | eeg_eye.data:download:29 - File exists
2026-03-22 16:19:15.338 | INFO     | eeg_eye.data:download:29 - File exists


209 60
