In [1]:
%load_ext autoreload
%autoreload 2

from eeg_eye.dataset import EEGEyeDataset
from eeg_eye.data import load
import numpy as np

In [ ]:
data_set = EEGEyeDataset()

2026-03-22 10:09:29.247 | INFO     | eeg_eye.data:download:29 - File exists


In [ ]:
window = 50
stride = 50

In [ ]:
cumcount = np.concatenate([[0], data_set.cumulative_count])
cumcount

array([  0,   0,   2,  14,  22,  27,  36,  44,  48,  48,  55,  74,  90,
       102, 115, 162, 202, 220, 232, 232, 235, 235, 257, 257, 269, 269])

In [ ]:
idx = 0

search = np.searchsorted(cumcount, idx, side='right')
previous_len = cumcount[search - 1]
window = data_set[idx - previous_len]

In [ ]:
window

(tensor([[4424.1001, 4087.6899, 4311.2798,  ..., 4314.8701, 4675.8999,
          4466.6699],
         [4426.1499, 4087.1799, 4314.8701,  ..., 4320.5098, 4692.3101,
          4474.8701],
         [4417.9502, 4081.5400, 4310.7700,  ..., 4318.4600, 4693.8501,
          4462.5601],
         ...,
         [4322.0498, 4034.8701, 4280.0000,  ..., 4291.7900, 4617.4399,
          4375.8999],
         [4315.8999, 4031.7900, 4275.3799,  ..., 4285.6401, 4618.4600,
          4376.9199],
         [4315.8999, 4027.6899, 4275.8999,  ..., 4282.0498, 4618.4600,
          4374.3599]]),
 tensor(0.))

In [ ]:
data_set[1]

(tensor([[4312.3101, 4022.0500, 4278.4600, 4149.2300, 4336.9199, 4623.5898,
          4081.5400, 4639.4902, 4214.3599, 4230.7700, 4186.6699, 4284.6201,
          4612.3101, 4368.2100],
         [4304.1001, 4016.9199, 4273.8501, 4145.1299, 4340.0000, 4623.5898,
          4084.1001, 4646.6699, 4223.0801, 4229.2300, 4182.0498, 4282.5601,
          4606.1499, 4364.1001],
         [4303.0801, 4016.9199, 4270.7700, 4138.9702, 4342.0498, 4621.5400,
          4082.5601, 4645.6401, 4220.0000, 4229.2300, 4180.5098, 4276.9199,
          4602.0498, 4362.5601],
         [4304.6201, 4018.4600, 4272.3101, 4139.4902, 4340.0000, 4619.4902,
          4082.5601, 4637.9502, 4203.0801, 4226.6699, 4179.4902, 4278.4600,
          4602.0498, 4360.0000],
         [4301.0298, 4013.8501, 4268.7202, 4140.0000, 4341.0298, 4617.4399,
          4082.0500, 4626.1499, 4196.4102, 4224.1001, 4177.9502, 4278.9702,
          4603.0801, 4360.0000],
         [4300.0000, 4009.2300, 4263.5898, 4138.4600, 4342.5601, 4617.9502,